services:
  php:
    build:
      context: .
      dockerfile: PhpFpm.Dockerfile
    container_name: php-fpm_UTN
    volumes:
      - ../aplicacion-web:/var/www/html
    environment:
      - TZ=America/Argentina/Buenos_Aires

  nginx:
    image: nginx:1.24
    container_name: nginx_UTN
    ports:
      - "80:80"
    volumes:
      - ./configNginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../aplicacion-web:/var/www/html
    depends_on:
      php:
        condition: service_started
      db:
        condition: service_healthy

  db:
    image: mysql:8.4.2
    container_name: db_UTN
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mi_banco_db
      TZ: America/Argentina/Buenos_Aires
    volumes:
      - ../bDContenedor:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 10

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin_UTN
    environment:
      PMA_HOST: db_UTN
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      db:
        condition: service_healthy
